/**
 * Converts OpenAPI response schemas to TypeScript type declarations.
 * Generates a .d.ts file with typed overloads for tyFetch().
 */

// Minimal OpenAPI types for schema traversal
interface OpenAPISchema {
  type?: string;
  properties?: Record<string, OpenAPISchema>;
  items?: OpenAPISchema;
  required?: string[];
  $ref?: string;
  enum?: (string | number | boolean)[];
  oneOf?: OpenAPISchema[];
  anyOf?: OpenAPISchema[];
  allOf?: OpenAPISchema[];
  additionalProperties?: boolean | OpenAPISchema;
  description?: string;
  nullable?: boolean;
}

interface OpenAPIOperation {
  responses?: Record<
    string,
    {
      content?: Record<string, { schema?: OpenAPISchema; example?: unknown }>;
      description?: string;
    }
  >;
  requestBody?: {
    content?: Record<string, { schema?: OpenAPISchema }>;
    required?: boolean;
  };
  parameters?: Array<{
    name?: string;
    in?: string;
    required?: boolean;
    schema?: OpenAPISchema;
    $ref?: string;
  }>;
  summary?: string;
}

interface FullOpenAPISpec {
  paths: Record<string, Record<string, OpenAPIOperation>>;
  components?: {
    schemas?: Record<string, OpenAPISchema>;
    securitySchemes?: Record<string, { type?: string; in?: string; name?: string; description?: string }>;
  };
  security?: Array<Record<string, string[]>>;
  servers?: Array<{ url?: string }>;
  info?: { title?: string; version?: string };
}

export interface DomainSpec {
  domain: string;
  baseUrl: string; // e.g. "https://api.stripe.com"
  basePath: string; // e.g. "" or "/api/v3"
  spec: FullOpenAPISpec;
}

/** Generate one .d.ts per domain, filtered to only paths matching URLs seen in the codebase. */
export function generatePerDomain(
  domainSpecs: DomainSpec[],
  usedUrls: Array<{ domain: string; path: string }>,
): Map<string, string> {
  const result = new Map<string, string>();

  // Group used paths by domain
  const usedByDomain = new Map<string, string[]>();
  for (const { domain, path } of usedUrls) {
    const existing = usedByDomain.get(domain) ?? [];
    existing.push(path);
    usedByDomain.set(domain, existing);
  }

  for (const ds of domainSpecs) {
    const safeDomain = ds.domain.replace(/[^a-zA-Z0-9]/g, "_");
    const usedPaths = usedByDomain.get(ds.domain) ?? [];

    if (usedPaths.length === 0) continue; // no fetch calls for this domain

    // Filter spec paths to only those that match used URLs
    const basePath = ds.basePath;
    const filteredPaths: Record<string, any> = {};

    for (const [specPath, methods] of Object.entries(ds.spec.paths)) {
      const fullSpecPath = basePath + specPath;
      const matches = usedPaths.some((usedPath) => {
        // Exact match
        if (usedPath === fullSpecPath) return true;
        // Template match: /repos/{owner}/{repo} matches /repos/anthropics/claude-code
        const specParts = fullSpecPath.split("/");
        const usedParts = usedPath.split("/");
        if (specParts.length !== usedParts.length) return false;
        return specParts.every((sp, i) => sp.startsWith("{") || sp === usedParts[i]);
      });
      if (matches) filteredPaths[specPath] = methods;
    }

    if (Object.keys(filteredPaths).length === 0) continue;

    const filteredSpec = { ...ds, spec: { ...ds.spec, paths: filteredPaths } };
    result.set(`${safeDomain}.d.ts`, generateDtsContent([filteredSpec]));
  }
  return result;
}

/** Generate the full .d.ts file content with typed overloads for the given domain specs. */
export function generateDtsContent(domainSpecs: DomainSpec[]): string {
  const lines: string[] = [
    "// Auto-generated by ty-fetch plugin. Do not edit.",
    "// This file provides typed overloads for tyFetch() based on loaded OpenAPI specs.",
    "",
  ];

  // Collect type definitions and overloads — split per domain into separate files
  const typeDefinitions: string[] = [];
  const overloads: string[] = [];
  const typeNameCounter = new Map<string, number>();

  for (const ds of domainSpecs) {
    const { spec, domain, baseUrl, basePath } = ds;
    const resolver = (ref: string) => resolveRef(spec, ref);

    for (const [path, methods] of Object.entries(spec.paths)) {
      const methodOrder = ["get", "post", "put", "patch", "delete"];
      const sortedMethods = Object.entries(methods).sort(([a], [b]) => {
        const ai = methodOrder.indexOf(a);
        const bi = methodOrder.indexOf(b);
        return (ai === -1 ? 99 : ai) - (bi === -1 ? 99 : bi);
      });

      for (const [method, operation] of sortedMethods) {
        if (["parameters", "summary", "description"].includes(method)) continue;
        if (!operation?.responses) continue;

        const successResp = operation.responses["200"] ?? operation.responses["201"];
        // OpenAPI 3.x: content.application/json.schema
        // Swagger 2.0: schema directly on response
        const jsonContent = successResp?.content?.["application/json"];
        const swagger2Schema = (successResp as any)?.schema;
        if (!jsonContent?.schema && !jsonContent?.example && !swagger2Schema) continue;

        const schema = jsonContent?.schema ?? swagger2Schema ?? inferSchemaFromExample(jsonContent?.example);
        const fullUrl = `${baseUrl}${basePath}${path}`;

        const baseName = sanitizeTypeName(domain, path, method);
        const count = typeNameCounter.get(baseName) ?? 0;
        typeNameCounter.set(baseName, count + 1);
        const typeName = count > 0 ? `${baseName}_${count}` : baseName;

        const typeBody = schemaToType(schema, resolver, 1);
        const opDesc = (operation as any).summary ?? (operation as any).description;
        if (opDesc) {
          typeDefinitions.push(`  /** ${method.toUpperCase()} ${path} — ${opDesc.replace(/\*\//g, "* /")} */`);
        }
        typeDefinitions.push(`  type ${typeName} = ${typeBody};`);

        // ── Body type ──
        // OpenAPI 3.x: requestBody.content.application/json.schema
        // Swagger 2.0: parameters with in: body
        const swagger2BodyParam = (operation.parameters ?? []).find((p: any) => {
          const resolved = p.$ref ? resolveRef(spec, p.$ref) : p;
          return resolved?.in === "body";
        });
        const reqBodySchema =
          operation.requestBody?.content?.["application/json"]?.schema ??
          operation.requestBody?.content?.["application/x-www-form-urlencoded"]?.schema ??
          (swagger2BodyParam as any)?.schema;
        let bodyTypeArg = "never";
        if (reqBodySchema) {
          const bodyTypeName = `${typeName}_Body`;
          typeDefinitions.push(`  type ${bodyTypeName} = ${schemaToType(reqBodySchema, resolver, 1)};`);
          bodyTypeArg = bodyTypeName;
        }

        // ── Path params type ──
        const pathParamNames = (path.match(/\{(\w+)\}/g) || []).map((p: string) => p.slice(1, -1));
        let pathParamsArg = "never";
        if (pathParamNames.length > 0) {
          const pathParamsTypeName = `${typeName}_PathParams`;
          const pathProps = pathParamNames.map((n: string) => `${safePropName(n)}: string`).join("; ");
          typeDefinitions.push(`  type ${pathParamsTypeName} = { ${pathProps} };`);
          pathParamsArg = pathParamsTypeName;
        }

        // ── Query params type ──
        const queryParams: Array<{ name: string; type: string; required: boolean; description?: string }> = [];
        // Collect from operation-level and path-level parameters
        const allParams = [...(operation.parameters ?? []), ...((spec.paths[path] as any)?.parameters ?? [])];
        for (const param of allParams) {
          const resolved = param.$ref ? resolveRef(spec, param.$ref) : param;
          if (resolved?.in === "query") {
            const paramSchema = resolved.schema?.$ref
              ? (resolveRef(spec, resolved.schema.$ref) ?? resolved.schema)
              : (resolved.schema ?? null);
            const tsType = inferParamType(paramSchema);
            queryParams.push({
              name: resolved.name,
              type: tsType,
              required: !!resolved.required,
              description: resolved.description,
            });
          }
        }
        let queryParamsArg = "never";
        if (queryParams.length > 0) {
          const queryParamsTypeName = `${typeName}_QueryParams`;
          const queryPropLines: string[] = [];
          for (const q of queryParams) {
            if (q.description) queryPropLines.push(`/** ${q.description.replace(/\*\//g, "* /")} */`);
            queryPropLines.push(`${safePropName(q.name)}${q.required ? "" : "?"}: ${q.type};`);
          }
          typeDefinitions.push(`  type ${queryParamsTypeName} = { ${queryPropLines.join(" ")} };`);
          queryParamsArg = queryParamsTypeName;
        }

        // ── Headers type (from security schemes + header params) ──
        const headerProps: Array<{ name: string; description?: string; required: boolean }> = [];
        // Collect from header parameters
        for (const param of allParams) {
          const resolved = param.$ref ? resolveRef(spec, param.$ref) : param;
          if (resolved?.in === "header") {
            headerProps.push({ name: resolved.name, description: resolved.description, required: !!resolved.required });
          }
        }
        // Collect from security schemes
        const opSecurity = (operation as any).security ?? spec.security;
        if (opSecurity && spec.components?.securitySchemes) {
          for (const req of opSecurity) {
            for (const schemeName of Object.keys(req)) {
              const scheme = spec.components.securitySchemes[schemeName];
              if (scheme?.type === "apiKey" && scheme.in === "header" && scheme.name) {
                if (!headerProps.some((h) => h.name === scheme.name)) {
                  headerProps.push({ name: scheme.name, description: scheme.description, required: true });
                }
              }
            }
          }
        }
        let headersArg = "Record<string, string>";
        if (headerProps.length > 0) {
          const headersTypeName = `${typeName}_Headers`;
          const headerPropLines: string[] = [];
          for (const h of headerProps) {
            if (h.description) headerPropLines.push(`/** ${h.description.replace(/\*\//g, "* /")} */`);
            headerPropLines.push(`${safePropName(h.name)}${h.required ? "" : "?"}: string;`);
          }
          typeDefinitions.push(`  type ${headersTypeName} = { ${headerPropLines.join(" ")} };`);
          headersArg = headersTypeName;
        }

        const optionsType = `Options<${bodyTypeArg}, ${pathParamsArg}, ${queryParamsArg}, ${headersArg}>`;
        const resultType = `Promise<FetchResult<${typeName}>>`;

        // Full URL overload (for direct ty.get("https://...") calls)
        overloads.push(
          `    ${method}(url: \`${escapeTemplateUrl(fullUrl)}\`, options?: ${optionsType}): ${resultType};`,
        );
        // Relative path overloads (for ty.create({ prefixUrl }) instance calls)
        const relWithBase = `${basePath}${path}`;
        overloads.push(
          `    ${method}(url: \`${escapeTemplateUrl(relWithBase)}\`, options?: ${optionsType}): ${resultType};`,
        );
        if (basePath) {
          // Also emit without basePath for instances that include basePath in prefixUrl
          overloads.push(
            `    ${method}(url: \`${escapeTemplateUrl(path)}\`, options?: ${optionsType}): ${resultType};`,
          );
        }
        // Don't break — emit an overload per HTTP method
      }
    }
  }

  lines.push("// Response types");
  lines.push(
    ...typeDefinitions.map((l) => (l.startsWith("  type ") ? l.replace(/^ {2}/, "export ") : l.replace(/^ {2}/, ""))),
  );
  lines.push("");
  lines.push("export interface TyFetch {");
  lines.push(...overloads.map((l) => l.replace(/^ {4}/, "  ")));
  lines.push("}");

  return lines.join("\n");
}

/** Infer a TypeScript type string from an OpenAPI parameter schema, including enum unions and arrays. */
function inferParamType(paramSchema: OpenAPISchema | null | undefined): string {
  if (!paramSchema) return "string";

  // Enum → string literal union
  if (paramSchema.enum && paramSchema.enum.length > 0) {
    return paramSchema.enum
      .map((v) => (typeof v === "string" ? `"${v}"` : String(v)))
      .join(" | ");
  }

  // Array with items
  if (paramSchema.type === "array" && paramSchema.items) {
    const itemType = inferParamType(paramSchema.items);
    return `(${itemType})[]`;
  }

  if (paramSchema.type === "integer" || paramSchema.type === "number") return "number";
  if (paramSchema.type === "boolean") return "boolean";
  return "string";
}

function resolveRef(spec: FullOpenAPISpec, ref: string): OpenAPISchema | undefined {
  // Handle #/components/schemas/Foo
  const match = ref.match(/^#\/components\/schemas\/(.+)$/);
  if (!match) return undefined;
  return spec.components?.schemas?.[match[1]];
}

/** Infer an OpenAPI schema from a JSON example value. */
function inferSchemaFromExample(example: unknown): OpenAPISchema {
  if (example === null || example === undefined) return { type: "string" };
  if (typeof example === "string") return { type: "string" };
  if (typeof example === "number") return { type: "number" };
  if (typeof example === "boolean") return { type: "boolean" };
  if (Array.isArray(example)) {
    return { type: "array", items: example.length > 0 ? inferSchemaFromExample(example[0]) : { type: "string" } };
  }
  if (typeof example === "object") {
    const properties: Record<string, OpenAPISchema> = {};
    for (const [key, value] of Object.entries(example as Record<string, unknown>)) {
      properties[key] = inferSchemaFromExample(value);
    }
    return { type: "object", properties };
  }
  return { type: "string" };
}

function schemaToType(
  schema: OpenAPISchema,
  resolver: (ref: string) => OpenAPISchema | undefined,
  depth: number,
): string {
  // Depth limit to avoid huge nested types
  if (depth > 4) return "any";

  const nullable = schema.nullable ? " | null" : "";

  const indent = "  ".repeat(depth + 1);
  const outerIndent = "  ".repeat(depth);

  // Handle $ref
  if (schema.$ref) {
    const resolved = resolver(schema.$ref);
    if (!resolved) return "any";
    return schemaToType(resolved, resolver, depth);
  }

  // Handle enum
  if (schema.enum) {
    return schema.enum.map((v) => JSON.stringify(v)).join(" | ");
  }

  // Handle oneOf/anyOf
  if (schema.oneOf || schema.anyOf) {
    const variants = (schema.oneOf ?? schema.anyOf)!;
    return variants.map((v) => schemaToType(v, resolver, depth)).join(" | ");
  }

  // Handle allOf (intersection)
  if (schema.allOf) {
    return schema.allOf.map((v) => schemaToType(v, resolver, depth)).join(" & ");
  }

  // Handle object
  if (schema.type === "object" || schema.properties) {
    const props = schema.properties ?? {};
    const required = new Set(schema.required ?? []);
    const propLines: string[] = [];

    for (const [key, propSchema] of Object.entries(props)) {
      const optional = required.has(key) ? "" : "?";
      const propType = schemaToType(propSchema, resolver, depth + 1);
      if (propSchema.description) {
        propLines.push(`${indent}/** ${propSchema.description.replace(/\*\//g, "* /")} */`);
      }
      propLines.push(`${indent}${safePropName(key)}${optional}: ${propType};`);
    }

    if (schema.additionalProperties) {
      const valType =
        typeof schema.additionalProperties === "object"
          ? schemaToType(schema.additionalProperties, resolver, depth + 1)
          : "any";
      propLines.push(`${indent}[key: string]: ${valType};`);
    }

    if (propLines.length === 0) {
      return "Record<string, any>";
    }

    return `{\n${propLines.join("\n")}\n${outerIndent}}` + nullable;
  }

  // Handle array
  if (schema.type === "array") {
    const itemType = schema.items ? schemaToType(schema.items, resolver, depth) : "any";
    // Wrap complex types in parens
    return itemType.includes("|") || itemType.includes("&") ? `(${itemType})[]` : `${itemType}[]`;
  }

  // Primitives
  switch (schema.type) {
    case "string":
      return "string" + nullable;
    case "integer":
    case "number":
      return "number" + nullable;
    case "boolean":
      return "boolean" + nullable;
    case "null":
      return "null";
    default:
      return "any";
  }
}

function sanitizeTypeName(domain: string, path: string, method: string): string {
  // Convert "api.stripe.com" + "/v1/customers" + "get" → "Stripe_V1_Customers_Get"
  const domainPart = domain
    .replace(/^api\./, "")
    .replace(/\.\w+$/, "")
    .replace(/[^a-zA-Z0-9]/g, "_");
  const pathPart = path
    .replace(/[{}]/g, "")
    .split("/")
    .filter(Boolean)
    .map((s) => s.replace(/[^a-zA-Z0-9]/g, "_"))
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("_");
  const methodPart = method.charAt(0).toUpperCase() + method.slice(1);
  return `${capitalize(domainPart)}_${pathPart}_${methodPart}`;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

const TS_RESERVED = new Set([
  "break",
  "case",
  "catch",
  "class",
  "const",
  "continue",
  "debugger",
  "default",
  "delete",
  "do",
  "else",
  "enum",
  "export",
  "extends",
  "false",
  "finally",
  "for",
  "function",
  "if",
  "import",
  "in",
  "instanceof",
  "new",
  "null",
  "return",
  "super",
  "switch",
  "this",
  "throw",
  "true",
  "try",
  "typeof",
  "var",
  "void",
  "while",
  "with",
  "as",
  "implements",
  "interface",
  "let",
  "package",
  "private",
  "protected",
  "public",
  "static",
  "yield",
]);

function safePropName(key: string): string {
  if (TS_RESERVED.has(key)) return `"${key}"`;
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key) ? key : `"${key}"`;
}

function escapeTemplateUrl(url: string): string {
  // Replace {param} with ${string} for template literal matching
  return url.replace(/\{[^}]+\}/g, "${string}");
}
