/**
 * Converts OpenAPI response schemas to TypeScript type declarations.
 * Generates a .d.ts file with typed overloads for typedFetch().
 */

// Minimal OpenAPI types for schema traversal
interface OpenAPISchema {
  type?: string;
  properties?: Record<string, OpenAPISchema>;
  items?: OpenAPISchema;
  required?: string[];
  $ref?: string;
  enum?: (string | number | boolean)[];
  oneOf?: OpenAPISchema[];
  anyOf?: OpenAPISchema[];
  allOf?: OpenAPISchema[];
  additionalProperties?: boolean | OpenAPISchema;
  description?: string;
  nullable?: boolean;
}

interface OpenAPIOperation {
  responses?: Record<
    string,
    {
      content?: Record<string, { schema?: OpenAPISchema }>;
      description?: string;
    }
  >;
  summary?: string;
}

interface FullOpenAPISpec {
  paths: Record<string, Record<string, OpenAPIOperation>>;
  components?: { schemas?: Record<string, OpenAPISchema> };
  servers?: Array<{ url?: string }>;
  info?: { title?: string; version?: string };
}

interface DomainSpec {
  domain: string;
  baseUrl: string; // e.g. "https://api.stripe.com"
  basePath: string; // e.g. "" or "/api/v3"
  spec: FullOpenAPISpec;
}

export function generateDtsContent(domainSpecs: DomainSpec[]): string {
  const lines: string[] = [
    "// Auto-generated by typed-fetch plugin. Do not edit.",
    "// This file provides typed overloads for typedFetch() based on loaded OpenAPI specs.",
    "",
  ];

  // Collect all type definitions and overloads
  const typeDefinitions: string[] = [];
  const overloads: string[] = [];
  const typeNameCounter = new Map<string, number>();

  for (const ds of domainSpecs) {
    const { spec, domain, baseUrl, basePath } = ds;
    const resolver = (ref: string) => resolveRef(spec, ref);

    for (const [path, methods] of Object.entries(spec.paths)) {
      // Find the first operation with a response schema (prefer GET)
      const methodOrder = ["get", "post", "put", "patch", "delete"];
      const sortedMethods = Object.entries(methods).sort(([a], [b]) => {
        const ai = methodOrder.indexOf(a);
        const bi = methodOrder.indexOf(b);
        return (ai === -1 ? 99 : ai) - (bi === -1 ? 99 : bi);
      });

      for (const [method, operation] of sortedMethods) {
        if (["parameters", "summary", "description"].includes(method)) continue;
        if (!operation?.responses) continue;

        const successResp =
          operation.responses["200"] ?? operation.responses["201"];
        if (!successResp?.content?.["application/json"]?.schema) continue;

        const schema = successResp.content["application/json"].schema;
        const fullUrl = `${baseUrl}${basePath}${path}`;

        const baseName = sanitizeTypeName(domain, path, method);
        const count = typeNameCounter.get(baseName) ?? 0;
        typeNameCounter.set(baseName, count + 1);
        const typeName = count > 0 ? `${baseName}_${count}` : baseName;

        const typeBody = schemaToType(schema, resolver, 1);

        typeDefinitions.push(`  interface ${typeName} ${typeBody}`);
        overloads.push(
          `  export function typedFetch(url: \`${escapeTemplateUrl(fullUrl)}\`, init?: RequestInit): Promise<${typeName}>;`
        );
        break; // one overload per path — use the first match (GET preferred)
      }
    }
  }

  lines.push("declare module 'typed-fetch' {");
  lines.push("  // Response types");
  lines.push(...typeDefinitions);
  lines.push("");
  lines.push("  // Typed overloads (most specific first)");
  lines.push(...overloads);
  lines.push("");
  lines.push(
    "  // Fallback for unknown URLs",
    "  export function typedFetch(url: string, init?: RequestInit): Promise<unknown>;",
  );
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

function resolveRef(
  spec: FullOpenAPISpec,
  ref: string
): OpenAPISchema | undefined {
  // Handle #/components/schemas/Foo
  const match = ref.match(/^#\/components\/schemas\/(.+)$/);
  if (!match) return undefined;
  return spec.components?.schemas?.[match[1]];
}

function schemaToType(
  schema: OpenAPISchema,
  resolver: (ref: string) => OpenAPISchema | undefined,
  depth: number
): string {
  // Depth limit to avoid huge nested types
  if (depth > 3) return "any";

  const indent = "  ".repeat(depth + 1);
  const outerIndent = "  ".repeat(depth);

  // Handle $ref
  if (schema.$ref) {
    const resolved = resolver(schema.$ref);
    if (!resolved) return "any";
    return schemaToType(resolved, resolver, depth);
  }

  // Handle enum
  if (schema.enum) {
    return schema.enum.map((v) => JSON.stringify(v)).join(" | ");
  }

  // Handle oneOf/anyOf
  if (schema.oneOf || schema.anyOf) {
    const variants = (schema.oneOf ?? schema.anyOf)!;
    return variants
      .map((v) => schemaToType(v, resolver, depth))
      .join(" | ");
  }

  // Handle allOf (intersection)
  if (schema.allOf) {
    return schema.allOf
      .map((v) => schemaToType(v, resolver, depth))
      .join(" & ");
  }

  // Handle object
  if (schema.type === "object" || schema.properties) {
    const props = schema.properties ?? {};
    const required = new Set(schema.required ?? []);
    const propLines: string[] = [];

    for (const [key, propSchema] of Object.entries(props)) {
      const optional = required.has(key) ? "" : "?";
      const propType = schemaToType(propSchema, resolver, depth + 1);
      propLines.push(`${indent}${safePropName(key)}${optional}: ${propType};`);
    }

    if (schema.additionalProperties) {
      const valType =
        typeof schema.additionalProperties === "object"
          ? schemaToType(schema.additionalProperties, resolver, depth + 1)
          : "any";
      propLines.push(`${indent}[key: string]: ${valType};`);
    }

    if (propLines.length === 0) {
      return "Record<string, any>";
    }

    return `{\n${propLines.join("\n")}\n${outerIndent}}`;
  }

  // Handle array
  if (schema.type === "array") {
    const itemType = schema.items
      ? schemaToType(schema.items, resolver, depth)
      : "any";
    // Wrap complex types in parens
    return itemType.includes("|") || itemType.includes("&")
      ? `(${itemType})[]`
      : `${itemType}[]`;
  }

  // Primitives
  switch (schema.type) {
    case "string":
      return "string";
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    default:
      return "any";
  }
}

function sanitizeTypeName(domain: string, path: string, method: string): string {
  // Convert "api.stripe.com" + "/v1/customers" + "get" → "Stripe_V1_Customers_Get"
  const domainPart = domain
    .replace(/^api\./, "")
    .replace(/\.\w+$/, "")
    .replace(/[^a-zA-Z0-9]/g, "_");
  const pathPart = path
    .replace(/[{}]/g, "")
    .split("/")
    .filter(Boolean)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("_");
  const methodPart = method.charAt(0).toUpperCase() + method.slice(1);
  return `${capitalize(domainPart)}_${pathPart}_${methodPart}`;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function safePropName(key: string): string {
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key) ? key : `"${key}"`;
}

function escapeTemplateUrl(url: string): string {
  // Replace {param} with ${string} for template literal matching
  return url.replace(/\{[^}]+\}/g, "${string}");
}
