/**
 * Converts OpenAPI response schemas to TypeScript type declarations.
 * Generates a .d.ts file with typed overloads for typedFetch().
 */

// Minimal OpenAPI types for schema traversal
interface OpenAPISchema {
  type?: string;
  properties?: Record<string, OpenAPISchema>;
  items?: OpenAPISchema;
  required?: string[];
  $ref?: string;
  enum?: (string | number | boolean)[];
  oneOf?: OpenAPISchema[];
  anyOf?: OpenAPISchema[];
  allOf?: OpenAPISchema[];
  additionalProperties?: boolean | OpenAPISchema;
  description?: string;
  nullable?: boolean;
}

interface OpenAPIOperation {
  responses?: Record<
    string,
    {
      content?: Record<string, { schema?: OpenAPISchema }>;
      description?: string;
    }
  >;
  requestBody?: {
    content?: Record<string, { schema?: OpenAPISchema }>;
    required?: boolean;
  };
  summary?: string;
}

interface FullOpenAPISpec {
  paths: Record<string, Record<string, OpenAPIOperation>>;
  components?: { schemas?: Record<string, OpenAPISchema> };
  servers?: Array<{ url?: string }>;
  info?: { title?: string; version?: string };
}

export interface DomainSpec {
  domain: string;
  baseUrl: string; // e.g. "https://api.stripe.com"
  basePath: string; // e.g. "" or "/api/v3"
  spec: FullOpenAPISpec;
}

/**
 * Generate one .d.ts per domain — keeps each file under TS overload limits.
 * Returns a map of filename → content.
 */
const MAX_OVERLOADS_PER_FILE = 400;

/**
 * Filter spec paths to only those matching URLs seen in the codebase.
 * usedUrls is a Set of parsed { domain, path } objects.
 */
export function generatePerDomain(
  domainSpecs: DomainSpec[],
  usedUrls: Array<{ domain: string; path: string }>
): Map<string, string> {
  const result = new Map<string, string>();

  // Group used paths by domain
  const usedByDomain = new Map<string, string[]>();
  for (const { domain, path } of usedUrls) {
    const existing = usedByDomain.get(domain) ?? [];
    existing.push(path);
    usedByDomain.set(domain, existing);
  }

  for (const ds of domainSpecs) {
    const safeDomain = ds.domain.replace(/[^a-zA-Z0-9]/g, "_");
    const usedPaths = usedByDomain.get(ds.domain) ?? [];

    if (usedPaths.length === 0) continue; // no fetch calls for this domain

    // Filter spec paths to only those that match used URLs
    const basePath = ds.basePath;
    const filteredPaths: Record<string, any> = {};

    for (const [specPath, methods] of Object.entries(ds.spec.paths)) {
      const fullSpecPath = basePath + specPath;
      const matches = usedPaths.some((usedPath) => {
        // Exact match
        if (usedPath === fullSpecPath) return true;
        // Template match: /repos/{owner}/{repo} matches /repos/anthropics/claude-code
        const specParts = fullSpecPath.split("/");
        const usedParts = usedPath.split("/");
        if (specParts.length !== usedParts.length) return false;
        return specParts.every((sp, i) => sp.startsWith("{") || sp === usedParts[i]);
      });
      if (matches) filteredPaths[specPath] = methods;
    }

    if (Object.keys(filteredPaths).length === 0) continue;

    const filteredSpec = { ...ds, spec: { ...ds.spec, paths: filteredPaths } };
    result.set(`${safeDomain}.d.ts`, generateDtsContent([filteredSpec]));
  }
  return result;
}

export function generateDtsContent(domainSpecs: DomainSpec[]): string {
  const lines: string[] = [
    "// Auto-generated by typed-fetch plugin. Do not edit.",
    "// This file provides typed overloads for typedFetch() based on loaded OpenAPI specs.",
    "",
  ];

  // Collect type definitions and overloads — split per domain into separate files
  const typeDefinitions: string[] = [];
  const overloads: string[] = [];
  const typeNameCounter = new Map<string, number>();

  for (const ds of domainSpecs) {
    const { spec, domain, baseUrl, basePath } = ds;
    const resolver = (ref: string) => resolveRef(spec, ref);

    for (const [path, methods] of Object.entries(spec.paths)) {
      const methodOrder = ["get", "post", "put", "patch", "delete"];
      const sortedMethods = Object.entries(methods).sort(([a], [b]) => {
        const ai = methodOrder.indexOf(a);
        const bi = methodOrder.indexOf(b);
        return (ai === -1 ? 99 : ai) - (bi === -1 ? 99 : bi);
      });

      for (const [method, operation] of sortedMethods) {
        if (["parameters", "summary", "description"].includes(method)) continue;
        if (!operation?.responses) continue;

        const successResp =
          operation.responses["200"] ?? operation.responses["201"];
        if (!successResp?.content?.["application/json"]?.schema) continue;

        const schema = successResp.content["application/json"].schema;
        const fullUrl = `${baseUrl}${basePath}${path}`;

        const baseName = sanitizeTypeName(domain, path, method);
        const count = typeNameCounter.get(baseName) ?? 0;
        typeNameCounter.set(baseName, count + 1);
        const typeName = count > 0 ? `${baseName}_${count}` : baseName;

        const typeBody = schemaToType(schema, resolver, 1);
        typeDefinitions.push(`  type ${typeName} = ${typeBody};`);

        // Check for request body schema (application/json or form-urlencoded)
        const reqBodySchema =
          operation.requestBody?.content?.["application/json"]?.schema ??
          operation.requestBody?.content?.["application/x-www-form-urlencoded"]?.schema;

        let optionsType = "Options";
        if (reqBodySchema) {
          const bodyTypeName = `${typeName}_Body`;
          const bodyTypeBody = schemaToType(reqBodySchema, resolver, 1);
          typeDefinitions.push(`  type ${bodyTypeName} = ${bodyTypeBody};`);
          optionsType = `Options<${bodyTypeName}>`;
        }

        overloads.push(
          `    ${method}(url: \`${escapeTemplateUrl(fullUrl)}\`, options?: ${optionsType}): ResponsePromise<${typeName}>;`
        );
        // Don't break — emit an overload per HTTP method
      }
    }
  }

  lines.push("// Response types");
  lines.push(...typeDefinitions.map((l) => l.replace(/^  /, "export ")));
  lines.push("");
  lines.push("export interface TypedFetch {");
  lines.push(...overloads.map((l) => l.replace(/^    /, "  ")));
  lines.push("}");

  return lines.join("\n");
}

function resolveRef(
  spec: FullOpenAPISpec,
  ref: string
): OpenAPISchema | undefined {
  // Handle #/components/schemas/Foo
  const match = ref.match(/^#\/components\/schemas\/(.+)$/);
  if (!match) return undefined;
  return spec.components?.schemas?.[match[1]];
}

function schemaToType(
  schema: OpenAPISchema,
  resolver: (ref: string) => OpenAPISchema | undefined,
  depth: number
): string {
  // Depth limit to avoid huge nested types
  if (depth > 2) return "any";

  const indent = "  ".repeat(depth + 1);
  const outerIndent = "  ".repeat(depth);

  // Handle $ref
  if (schema.$ref) {
    const resolved = resolver(schema.$ref);
    if (!resolved) return "any";
    return schemaToType(resolved, resolver, depth);
  }

  // Handle enum
  if (schema.enum) {
    return schema.enum.map((v) => JSON.stringify(v)).join(" | ");
  }

  // Handle oneOf/anyOf
  if (schema.oneOf || schema.anyOf) {
    const variants = (schema.oneOf ?? schema.anyOf)!;
    return variants
      .map((v) => schemaToType(v, resolver, depth))
      .join(" | ");
  }

  // Handle allOf (intersection)
  if (schema.allOf) {
    return schema.allOf
      .map((v) => schemaToType(v, resolver, depth))
      .join(" & ");
  }

  // Handle object
  if (schema.type === "object" || schema.properties) {
    const props = schema.properties ?? {};
    const required = new Set(schema.required ?? []);
    const propLines: string[] = [];

    for (const [key, propSchema] of Object.entries(props)) {
      const optional = required.has(key) ? "" : "?";
      const propType = schemaToType(propSchema, resolver, depth + 1);
      propLines.push(`${indent}${safePropName(key)}${optional}: ${propType};`);
    }

    if (schema.additionalProperties) {
      const valType =
        typeof schema.additionalProperties === "object"
          ? schemaToType(schema.additionalProperties, resolver, depth + 1)
          : "any";
      propLines.push(`${indent}[key: string]: ${valType};`);
    }

    if (propLines.length === 0) {
      return "Record<string, any>";
    }

    return `{\n${propLines.join("\n")}\n${outerIndent}}`;
  }

  // Handle array
  if (schema.type === "array") {
    const itemType = schema.items
      ? schemaToType(schema.items, resolver, depth)
      : "any";
    // Wrap complex types in parens
    return itemType.includes("|") || itemType.includes("&")
      ? `(${itemType})[]`
      : `${itemType}[]`;
  }

  // Primitives
  switch (schema.type) {
    case "string":
      return "string";
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    default:
      return "any";
  }
}

function sanitizeTypeName(domain: string, path: string, method: string): string {
  // Convert "api.stripe.com" + "/v1/customers" + "get" → "Stripe_V1_Customers_Get"
  const domainPart = domain
    .replace(/^api\./, "")
    .replace(/\.\w+$/, "")
    .replace(/[^a-zA-Z0-9]/g, "_");
  const pathPart = path
    .replace(/[{}]/g, "")
    .split("/")
    .filter(Boolean)
    .map((s) => s.replace(/[^a-zA-Z0-9]/g, "_"))
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("_");
  const methodPart = method.charAt(0).toUpperCase() + method.slice(1);
  return `${capitalize(domainPart)}_${pathPart}_${methodPart}`;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

const TS_RESERVED = new Set([
  "break", "case", "catch", "class", "const", "continue", "debugger",
  "default", "delete", "do", "else", "enum", "export", "extends", "false",
  "finally", "for", "function", "if", "import", "in", "instanceof", "new",
  "null", "return", "super", "switch", "this", "throw", "true", "try",
  "typeof", "var", "void", "while", "with", "as", "implements", "interface",
  "let", "package", "private", "protected", "public", "static", "yield",
]);

function safePropName(key: string): string {
  if (TS_RESERVED.has(key)) return `"${key}"`;
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key) ? key : `"${key}"`;
}

function escapeTemplateUrl(url: string): string {
  // Replace {param} with ${string} for template literal matching
  return url.replace(/\{[^}]+\}/g, "${string}");
}
